### ISSUE TITLE
Add support for UGEE EX07

### ISSUE THREAD

**Issue by CrimsonFork** [OpenTabletDriver/OpenTabletDriver#2412]
### Acknowledgements

- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

### Manufacturer

Ugee

### Product Name

EX07

### Device Width

203mm

### Device Height

126mm

### Pressure Levels

2048

### Lines per Inch (LPI)

5080

### Additional Information

Digimend [supports this tablet](https://digimend.github.io/tablets/Ugee_EX07)

### Diagnostic Information

[ugee_ex07.json](https://github.com/OpenTabletDriver/OpenTabletDriver/files/9442900/ugee_ex07.txt)

**Comment by jamesbt365** [comment]
Move [99-opentabletdriver.rules.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/9460873/99-opentabletdriver.rules.txt) to /etc/udev/rules.d/99-opentabletdriver.rules and remove the txt at the end (github won't accept .rules as a format for some reason) Then run `sudo udevadm control --reload-rules` and replug your tablet. Export another diagnostic after restarting the service for OpenTabletDriver

**Comment by CrimsonFork** [comment]
[ugee_ex07_udev_rules.json](https://github.com/OpenTabletDriver/OpenTabletDriver/files/9460977/ugee_ex07_udev_rules.json.txt)

Interestingly, as soon as I ran the command the tablet started working again, though I'm not sure if it's OpenTabletDriver's doing.

**Comment by CrimsonFork** [comment]
```bash
$ echo "blacklist hid_uclogic" | sudo tee -a /etc/modprobe.d/blacklist.conf
sudo rmmod hid_uclogic
blacklist hid_uclogic
rmmod: ERROR: Module hid_uclogic is not currently loaded
```

**Comment by jamesbt365** [comment]
restart otd once again and export another diagnostic

**Comment by CrimsonFork** [comment]
[ugee_ex07_udev_nohid_uclogic.json](https://github.com/OpenTabletDriver/OpenTabletDriver/files/9461267/ugee_ex07_udev_nohid_uclogic.json.txt)

**Comment by jamesbt365** [comment]
Create the directory /usr/share/OpenTabletDriver/Configurations, move 
[this](https://github.com/OpenTabletDriver/OpenTabletDriver/files/9461287/EX07.json.txt) file into it and remove the .txt at the end, it should now detect, when it does go into the `tablet > tablet debugger` and see if there is a dot on the visualizer when moving your pen about.

**Comment by CrimsonFork** [comment]
Doing that with hif_uclogic disabled spews out errors:

![Screenshot from 2022-08-31 14-24-14](https://user-images.githubusercontent.com/22666602/187677884-16ec447a-1ced-4586-b04f-c62e148f0e55.png)
![Screenshot from 2022-08-31 14-24-19](https://user-images.githubusercontent.com/22666602/187677889-6bd31766-01f4-403f-acf8-299314005c1a.png)

Although disabling it at runtime does at least make the name appear
![Screenshot from 2022-08-31 14-26-57](https://user-images.githubusercontent.com/22666602/187678140-17804488-ecb0-47fd-b012-1d9e6dc35dcc.png)

**Comment by jamesbt365** [comment]
could you get the stack trace from the daemon?

**Comment by CrimsonFork** [comment]
How do I do that? I tried looking up but there seems to be too much terminology I just don't know.

**Comment by jamesbt365** [comment]
get the log the daemon gives

**Comment by jamesbt365** [comment]
i think i know whats wrong anyway

**Comment by jamesbt365** [comment]
[EX07.json.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/9461600/EX07.json.txt)
replace the file with this one, remember to remove the .txt

**Comment by CrimsonFork** [comment]
Still fails in the same way. And I'm still unsure how to get the log, as /var/log doesn't seem to contain anything opentabletdriver related.

**Comment by jamesbt365** [comment]
correct way would be journalctl --user-unit opentabletdriver if you were running through the service, either way remove ~/.config/OpenTabletDriver and restart the service

**Comment by CrimsonFork** [comment]
Removed the config.

```bash
$ journalctl --user-unit opentabletdriver
Aug 31 14:59:47 s systemd[2205]: opentabletdriver.service: Scheduled restart job, restart counter is at 67.
Aug 31 14:59:47 s systemd[2205]: Stopped OpenTabletDriver Daemon.
Aug 31 14:59:47 s systemd[2205]: Started OpenTabletDriver Daemon.
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Info]        Searching for tablets...
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Configuration overrides exist in '/usr/share/OpenTabletDriver/Configurations', overriding built-in configurations.
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet '10moon 1060N'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Acepen AP 1060'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Artisul A1201'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Artisul AP604'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Artisul M0610 Pro'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Gaomon 1060 Pro'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Gaomon M106K Pro'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Gaomon M106K'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Gaomon M10K Pro'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Gaomon M10K'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Gaomon M1220'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Gaomon M1230'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Gaomon M6'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Gaomon PD1161'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Gaomon PD1560'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Gaomon PD1561'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Gaomon S56K'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Gaomon S620'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Gaomon S630'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Genius G-Pen 560'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Genius i608x'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Huion 420'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Huion G10T'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Huion GC610'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Huion GT-220 V2'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Huion GT-221 Pro'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Huion H1060P'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Huion H1161'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Huion H420'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Huion H420X'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Huion H430P'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Huion H580X'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Huion H610 Pro V2'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Huion H610 Pro'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Huion H610X'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Huion H640P'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Huion H642'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Huion H950P'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Huion HC16'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Huion HS610'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Huion HS611'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Huion HS64'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Huion HS95'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Huion Kamvas 13'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Huion Kamvas 16 (2021)'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Huion Kamvas 16'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Huion Kamvas 20'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Huion Kamvas 22 Plus'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Huion Kamvas Pro 12'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Huion Kamvas Pro 13 (2.5k)'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Huion Kamvas Pro 13'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Huion Kamvas Pro 16'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Huion Kamvas Pro 20'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Huion Kamvas Pro 24'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Huion New 1060 Plus (2048)'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Huion New 1060 Plus'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Huion Q11K V2'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Huion Q11K'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Huion Q620M'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Huion WH1409 V2'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Huion WH1409'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Parblo A609'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Parblo A610 Pro'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Parblo A640 V2'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Parblo Intangbo M'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Parblo Intangbo S'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Parblo Ninos M'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Parblo Ninos S'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'RobotPen T9A'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'UC-Logic 1060N'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'UC-Logic PF1209'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'UGEE U1600'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'UGTABLET M708'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'VEIKK A15 Pro'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'VEIKK A15'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'VEIKK A30'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'VEIKK A50 V2'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'VEIKK A50'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'VEIKK S640 V2'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'VEIKK S640'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'VEIKK VK640'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'ViewSonic Woodpad PF0730'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom CTE-430'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom CTE-440'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom CTE-450'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom CTE-460'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom CTE-630'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom CTE-640'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom CTE-650'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom CTF-430'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom CTH-460'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom CTH-461'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom CTH-470'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom CTH-480'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom CTH-490'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom CTH-661'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom CTH-670'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom CTH-680'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom CTH-690'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom CTL-4100'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom CTL-4100WL'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom CTL-460'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom CTL-470'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom CTL-471'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom CTL-472'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom CTL-480'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom CTL-490'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom CTL-6100'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom CTL-6100WL'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom CTL-671'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom CTL-672'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom CTL-680'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom CTL-690'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom DTC-133'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom ET-0405-U'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom ET-0405A-U'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom FT-0405-U'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom GD-0405-U'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom GD-0608-U'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom GD-0912-U'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom GD-1212-U'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom GD-1218-U'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom MTE-450'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom PTH-450'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom PTH-451'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom PTH-460'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom PTH-650'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom PTH-651'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom PTH-660'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom PTH-850'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom PTH-851'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom PTH-860'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom PTK-1240'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom PTK-440'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom PTK-450'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom PTK-540WL'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom PTK-640'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom PTK-650'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom PTK-840'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom PTZ-1230'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom PTZ-1231W'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom PTZ-430'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom PTZ-431W'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom PTZ-630'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom PTZ-631W'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom PTZ-930'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom XD-0405-U'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom XD-0608-U'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom XD-0912-U'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom XD-1212-U'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'Wacom XD-1218-U'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'XenceLabs Pen Tablet Medium'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'XenceLabs Pen Tablet Small'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'XENX P1-640'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'XENX P3-1060'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'XENX X1-640'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'XP-Pen Artist 12 (2nd Gen)'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'XP-Pen Artist 12 Pro'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'XP-Pen Artist 12'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'XP-Pen Artist 13.3 Pro'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'XP-Pen Artist 15.6 Pro'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'XP-Pen Artist 15.6'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'XP-Pen Artist 22HD'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'XP-Pen CT1060'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'XP-Pen CT430'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'XP-Pen CT640'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'XP-Pen Deco 01 V2 (variant 2)'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'XP-Pen Deco 01 V2'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'XP-Pen Deco 01'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'XP-Pen Deco 02'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'XP-Pen Deco 03'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'XP-Pen Deco mini4'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'XP-Pen Deco mini7'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'XP-Pen Deco Pro Medium'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'XP-Pen Deco Pro Small'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'XP-Pen Innovator 16'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'XP-Pen Star 03'
Aug 31 14:59:47 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'XP-Pen Star 05 V3'
Aug 31 14:59:48 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'XP-Pen Star 06'
Aug 31 14:59:48 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'XP-Pen Star 06C'
Aug 31 14:59:48 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'XP-Pen Star G430'
Aug 31 14:59:48 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'XP-Pen Star G430S V2'
Aug 31 14:59:48 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'XP-Pen Star G430S'
Aug 31 14:59:48 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'XP-Pen Star G540 Pro'
Aug 31 14:59:48 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'XP-Pen Star G540'
Aug 31 14:59:48 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'XP-Pen Star G640 V2'
Aug 31 14:59:48 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'XP-Pen Star G640'
Aug 31 14:59:48 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'XP-Pen Star G640S'
Aug 31 14:59:48 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'XP-Pen Star G960'
Aug 31 14:59:48 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'XP-Pen Star G960S Plus'
Aug 31 14:59:48 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'XP-Pen Star G960S'
Aug 31 14:59:48 s OpenTabletDriver.Daemon[50859]: [Detect:Debug]        Searching for tablet 'UGEE EX07'
Aug 31 14:59:48 s OpenTabletDriver.Daemon[50859]: [Detect:Warning]        More than 1 matching device has been found.
Aug 31 14:59:48 s OpenTabletDriver.Daemon[50859]: [Device:Debug]        Initializing device 'TABLET EX 07 ' /sys/devices/pci0000:00/0000:00:14.0/usb3/3-8/3-8:1.0/0003:28BD:0071.000B/hidraw/hidraw6
Aug 31 14:59:48 s OpenTabletDriver.Daemon[50859]: [Device:Debug]        Using report parser type 'OpenTabletDriver.Configurations.Parsers.XP_Pen.XP_PenReportParser'
Aug 31 14:59:48 s OpenTabletDriver.Daemon[50859]: [Device:Debug]        Set device output: 02-B0-04
Aug 31 14:59:48 s OpenTabletDriver.Daemon[50859]: [Detect:Info]        Found tablet 'UGEE EX07'
Aug 31 14:59:48 s OpenTabletDriver.Daemon[50859]: Unhandled exception. System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (99): Cannot assign requested address /run/user/1000/:0
Aug 31 14:59:48 s OpenTabletDriver.Daemon[50859]:    at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
Aug 31 14:59:48 s OpenTabletDriver.Daemon[50859]:    at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
Aug 31 14:59:48 s OpenTabletDriver.Daemon[50859]:    at WaylandNET.Client.WaylandClientConnection.ConnectToDisplay(String display)
Aug 31 14:59:48 s OpenTabletDriver.Daemon[50859]:    at WaylandNET.Client.WaylandClientConnection..ctor(String display)
Aug 31 14:59:48 s OpenTabletDriver.Daemon[50859]:    at OpenTabletDriver.Desktop.Interop.Display.WaylandDisplay..ctor()
Aug 31 14:59:48 s OpenTabletDriver.Daemon[50859]:    at OpenTabletDriver.Desktop.Interop.DesktopInterop.ConstructLinuxDisplay()
Aug 31 14:59:48 s OpenTabletDriver.Daemon[50859]:    at OpenTabletDriver.Desktop.Interop.DesktopInterop.get_VirtualScreen()
Aug 31 14:59:48 s OpenTabletDriver.Daemon[50859]:    at OpenTabletDriver.Desktop.Reflection.DesktopPluginManager.<>c.<ResetServices>b__30_5()
Aug 31 14:59:48 s OpenTabletDriver.Daemon[50859]:    at OpenTabletDriver.Desktop.Reflection.ServiceManager.GetService(Type serviceType)
Aug 31 14:59:48 s OpenTabletDriver.Daemon[50859]:    at OpenTabletDriver.Desktop.Reflection.ServiceManager.GetService[T]()
Aug 31 14:59:48 s OpenTabletDriver.Daemon[50859]:    at OpenTabletDriver.Desktop.Profiles.AbsoluteModeSettings.GetDefaults(DigitizerSpecifications digitizer)
Aug 31 14:59:48 s OpenTabletDriver.Daemon[50859]:    at OpenTabletDriver.Desktop.Profiles.Profile.GetDefaults(TabletReference tablet)
Aug 31 14:59:48 s OpenTabletDriver.Daemon[50859]:    at OpenTabletDriver.Desktop.Profiles.ProfileCollection.<>c.<.ctor>b__2_0(TabletReference s)
Aug 31 14:59:48 s OpenTabletDriver.Daemon[50859]:    at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
Aug 31 14:59:48 s OpenTabletDriver.Daemon[50859]:    at System.Linq.Enumerable.SelectIListIterator`2.MoveNext()
Aug 31 14:59:48 s OpenTabletDriver.Daemon[50859]:    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
Aug 31 14:59:48 s OpenTabletDriver.Daemon[50859]:    at System.Collections.ObjectModel.ObservableCollection`1.CreateCopy(IEnumerable`1 collection, String paramName)
Aug 31 14:59:48 s OpenTabletDriver.Daemon[50859]:    at System.Collections.ObjectModel.ObservableCollection`1..ctor(IEnumerable`1 collection)
Aug 31 14:59:48 s OpenTabletDriver.Daemon[50859]:    at OpenTabletDriver.Desktop.Profiles.ProfileCollection..ctor(IEnumerable`1 profiles)
Aug 31 14:59:48 s OpenTabletDriver.Daemon[50859]:    at OpenTabletDriver.Desktop.Profiles.ProfileCollection..ctor(IEnumerable`1 tablets)
Aug 31 14:59:48 s OpenTabletDriver.Daemon[50859]:    at OpenTabletDriver.Desktop.Settings.GetDefaultProfiles()
Aug 31 14:59:48 s OpenTabletDriver.Daemon[50859]:    at OpenTabletDriver.Desktop.Settings.GetDefaults()
Aug 31 14:59:48 s OpenTabletDriver.Daemon[50859]:    at OpenTabletDriver.Daemon.DriverDaemon.ResetSettings()
Aug 31 14:59:48 s OpenTabletDriver.Daemon[50859]:    at OpenTabletDriver.Daemon.DriverDaemon.LoadUserSettings()
Aug 31 14:59:48 s OpenTabletDriver.Daemon[50859]:    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
Aug 31 14:59:48 s OpenTabletDriver.Daemon[50859]:    at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
Aug 31 14:59:48 s OpenTabletDriver.Daemon[50859]:    at System.Threading.ThreadPoolWorkQueue.Dispatch()
Aug 31 14:59:48 s OpenTabletDriver.Daemon[50859]:    at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
Aug 31 14:59:48 s OpenTabletDriver.Daemon[50859]:    at System.Threading.Thread.StartCallback()
Aug 31 14:59:49 s systemd[2205]: opentabletdriver.service: Main process exited, code=killed, status=6/ABRT
Aug 31 14:59:49 s systemd[2205]: opentabletdriver.service: Failed with result 'signal'.
```

**Comment by jamesbt365** [comment]
Your environment is a little messed up i think but we can fix that after, for now stop the systemd user server and start it up manually with `dotnet /usr/share/OpenTabletDriver/OpenTabletDriver.Daemon.dll`

**Comment by CrimsonFork** [comment]
It works now, or at least it functions in that it doesn't crash and does show up in the debugger

**Comment by CrimsonFork** [comment]
Yes. `Position:[40640,25400]`

**Comment by jamesbt365** [comment]
max pressure when pressing the pen nib down?

**Comment by CrimsonFork** [comment]
2047

**Comment by jamesbt365** [comment]
I can't find a spec sheet but does this tablet have anything special like tilt, etc etc.

**Comment by CrimsonFork** [comment]
There's also a bug of some sort when the pen is approached from outside the zone from the top or right, or pressing a pen button while outside, making the pointer jump at almost the opposite edge until it's within the zone again, but that's not specific to OpenTabletDriver and I'm not sure how easy that would be to fix in software.

**Comment by jamesbt365** [comment]
[EX07.json.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/9461919/EX07.json.txt)
This configuration _might_ fix the buttons (i hope i don't need to change a parser) but about the teleportation while pressing pen buttons, yeah that can't be fixed in software.

**Comment by CrimsonFork** [comment]
Nope, it still crashes the thing
`(OpenTabletDriver.UX.Gtk:74718): Gtk-WARNING **: 15:36:13.986: __gtksharp_2_Eto_GtkSharp_Forms_EtoEventBox 0x562fb8aa6130 adjusted size vertical min 320 natural 320 must not decrease below min 343 natural 343`

```
[Tablet:Debug]	Tablet debugging is enabled
[IndexOutOfRangeException:Error]	Index was outside the bounds of the array.
   at OpenTabletDriver.Plugin.Tablet.TabletReport..ctor(Byte[] report)
   at OpenTabletDriver.Configurations.Parsers.XP_Pen.XP_PenReportParser.Parse(Byte[] report)
   at OpenTabletDriver.Devices.DeviceReader`1.Main()
[Tablet:Debug]	Tablet debugging is disabled
[IPC:Debug]	Disconnected from a client.

It only happens while it's outside the main area. it also goes to very specific coordinates, for horizontal tra

**Comment by CrimsonFork** [comment]
> but about the teleportation while pressing pen buttons, yeah that can't be fixed in software.

It only happens while it's outside the main area. it also goes to very specific coordinates, for horizontal travel there's just one X value and for vertical there's a very narrow range of Y values, so I though maybe it can be easily ignored when form one input in a specific X or Y range it jumps to another specified range.

**Comment by jamesbt365** [comment]
data is missing when the pen buttons are pressed, so you'll either get cursor teleportation or freezing entirely.

**Comment by jamesbt365** [comment]
As to it crashing on pressing aux, somebody who knows how to parse it will have to continue on from here.

**Comment by CrimsonFork** [comment]
It's much less of an issue when pressing the buttons and more that it's just something that happens when the pen is getting out of the designated field but is still picked up. Thank you for your help so far anyway.
